name: Build Container and Push to Docker Hub

on:
  push:
    branches:
      - 'params/VERSION'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Get Date
        id: getdate
        run: echo ::set-output name=date::$(date '+%Y-%m-%d')
      - 
        name: Get Name
        id: getname
        run: echo ::set-output name=containerName::$(cat params/NAME)
      - 
        name: Get Version
        id: getversion
        run: echo ::set-output name=version::$(cat params/VERSION)
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64,arm
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ secrets.DOCKER_USER }}/${{ steps.getname.outputs.containerName }}:latest, ${{ secrets.DOCKER_USER }}/${{ steps.getname.outputs.containerName }}:${{ steps.getversion.outputs.version }}
          build-args: VERSION=${{ steps.getversion.outputs.version }}